# using lets encrypt for ssl certificates
db:
  build: db
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  # uncomment the following to enable backup
  #environment:
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1
app:
  build: app
  links:
    - db:db
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
web:
  build: web-le
  ports:
    - "443:443"
  links:
    - app:platform
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/letsencrypt/live/example.com/fullchain.pem:/cert/cert.pem:ro
    - /etc/letsencrypt/live/example.com/privkey.pem:/cert/key-no-password.pem:ro
